name: Sync Release
on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.x

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Install
        run: pnpm install

      - name: Set up Git
        run: |
          git config user.name "Manuel Gonçalves"
          git config user.email "manuelmjgc@gmail.com"

      - name: Get Main Version
        id: get_main_version
        run: |
          git checkout main
          git pull
          echo "current_main_version=$(pnpm pkg get version | tr -d '\"' | tr -d '\-SNAPSHOT')" >> $GITHUB_OUTPUT

      - name: Get Develop Version
        id: get_develop_version
        run: |
          git checkout develop
          git pull
          echo "current_develop_version=$(pnpm pkg get version | tr -d '\"' | tr -d '\-SNAPSHOT')" >> $GITHUB_OUTPUT

      - name: Update Version
        id: update_version
        if: ${{steps.get_main_version.outputs.current_main_version == steps.get_develop_version.outputs.current_develop_version}}
        run: |
          echo "Correct Package Version"
          echo "version=$(pnpm version minor --no-git-tag-version)" >> $GITHUB_OUTPUT

      - name: Update Version Fallback
        id: update_version
        if: ${{steps.get_main_version.outputs.current_main_version != steps.get_develop_version.outputs.current_develop_version}}
        run: |
          echo "Problem comparing Package version, taking main branch version as ref"
          pnpm version ${{steps.get_main_version.outputs.current_main_version}} --no-git-tag-version
          echo "version=$(pnpm version minor --no-git-tag-version)" >> $GITHUB_OUTPUT

      - name: Update Changelog
        id: update_changelog
        run: |
          sed -i 's/Unreleased/${{ steps.update_version.outputs.version }}/g' CHANGELOG.md
